Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2022-08, with the labels that each got.

#2 KeyCloak integration
  package.json
  src/app/app.module.ts
  src/app/core/authentication/authentication.service.ts
  src/app/core/init/keycloak-init.factory.ts
  src/app/core/shell/sidenav/sidenav.component.ts
  src/app/home/home.component.ts
  src/app/settings/settings.service.ts
  src/app/web-app.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: size/L

#3 Ser 1103
  src/app/core/authentication/authentication.service.ts
  src/app/core/authentication/o-auth2-token.model.ts
  src/app/core/init/keycloak-init.factory.ts
Labels: size/XS

#6 SER-1106 OU Module: Treeview implementation of OUs
  src/app/core/authentication/authentication.guard.ts
  src/app/core/authentication/authentication.service.ts
  src/app/core/shell/sidenav/sidenav.component.ts
  src/app/core/shell/toolbar/toolbar.component.ts
  src/app/organization/offices/offices.component.html
  src/app/organization/offices/offices.component.ts
  src/app/shared/office-tree-view/office-tree-node.spec.ts
  src/app/shared/office-tree-view/office-tree-node.ts
  src/app/shared/office-tree-view/office-tree-view.component.html
  src/app/shared/office-tree-view/office-tree-view.component.scss
  src/app/shared/office-tree-view/office-tree-view.component.spec.ts
  src/app/shared/office-tree-view/office-tree-view.component.ts
  src/app/shared/shared.module.ts
  src/app/web-app.component.ts
  src/assets/env.js
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/index.html
Labels: size/L

#5 fix css related issues
  src/assets/env.js
  src/main.scss
  src/theme/styles/_align.scss
  src/theme/styles/_background.scss
  src/theme/styles/_border.scss
  src/theme/styles/_colours.scss
  src/theme/styles/_display.scss
  src/theme/styles/_float.scss
  src/theme/styles/_form.scss
  src/theme/styles/_helper.scss
  src/theme/styles/_loader.scss
  src/theme/styles/_margin.scss
  src/theme/styles/_misc.scss
  src/theme/styles/_overflow.scss
  src/theme/styles/_padding.scss
  src/theme/styles/_position.scss
  src/theme/styles/_status.scss
  src/theme/styles/_text.scss
  src/theme/styles/_width-height.scss
  src/theme/styles/_z-index.scss
Labels: size/XS

#8 Ser 1107
  src/app/core/http/error-handler.interceptor.ts
  src/app/organization/offices/create-office/create-office.component.html
  src/app/organization/offices/create-office/create-office.component.scss
  src/app/organization/offices/create-office/create-office.component.ts
  src/app/organization/offices/edit-office/edit-office.component.html
  src/app/organization/offices/edit-office/edit-office.component.scss
  src/app/organization/offices/edit-office/edit-office.component.ts
  src/app/organization/organization.service.ts
  src/app/shared/office-hierarchy/office-hierarchy.component.html
  src/app/shared/office-hierarchy/office-hierarchy.component.scss
  src/app/shared/office-hierarchy/office-hierarchy.component.spec.ts
  src/app/shared/office-hierarchy/office-hierarchy.component.ts
  src/app/shared/office-tree-view/office-tree-node.ts
  src/app/shared/office-tree-view/office-tree-view.component.html
  src/app/shared/office-tree-view/office-tree-view.component.scss
  src/app/shared/office-tree-view/office-tree-view.component.ts
  src/app/shared/shared.module.ts
  src/environments/.env.ts
  tsconfig.json
Labels: size/XL
