Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2023-02, with the labels that each got.

#44 SER-1517 component created for loan allocation products
  package.json
  src/app/app.module.ts
  src/app/notifications/notifications.service.ts
  src/app/products/loan-product-allocation-setting/loan-product-allocation-setting.component.html
  src/app/products/loan-product-allocation-setting/loan-product-allocation-setting.component.scss
  src/app/products/loan-product-allocation-setting/loan-product-allocation-setting.component.spec.ts
  src/app/products/loan-product-allocation-setting/loan-product-allocation-setting.component.ts
  src/app/products/loan-product-allocation-setting/loan-product-allocation.resolver.ts
  src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.html
  src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.scss
  src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.spec.ts
  src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.ts
  src/app/products/loan-product-allocation-setting/loan-product-and-template.resolver.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-charges-step/loan-product-charges-step.component.ts
  src/app/products/products-routing.module.ts
  src/app/products/products.component.html
  src/app/products/products.module.ts
  src/app/products/products.service.ts
  src/app/settings/settings.service.ts
  src/app/shared/country-tree-view/country-tree-view.component.ts
  src/app/shared/footer/footer.component.ts
  src/polyfills.ts
Labels: size/XL

#43 Ser-1550 upgrade to angular13
  .github/workflows/build.yml
  .gitignore
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/app/centers/centers-view/centers-view.component-theme.scss
  src/app/clients/clients-view/clients-view.component-theme.scss
  src/app/deposits/fixed-deposits/fixed-deposit-account-view/fixed-deposit-account-view.component-theme.scss
  src/app/deposits/recurring-deposits/recurring-deposits-account-view/recurring-deposits-account-view.component-theme.scss
  src/app/groups/groups-view/groups-view.component-theme.scss
  src/app/home/dashboard/dashboard.component-theme.scss
  src/app/loans/loans-view/loans-view.component-theme.scss
  src/app/savings/savings-account-view/savings-account-view.component-theme.scss
  src/app/shares/shares-account-view/shares-account-view.component-theme.scss
  src/environments/.env.ts
  src/theme/custom/denim-yellowgreen.scss
  src/theme/custom/pictonblue-yellowgreen.scss
  src/theme/deeppurple-amber.scss
  src/theme/indigo-pink.scss
  src/theme/pink-bluegrey.scss
  src/theme/purple-green.scss
Labels: size/L

#45 [SER-842] Allow an admin to select a country and make any changes to it
  RELEASE_NOTES.md
  src/app/core/shell/toolbar/toolbar.component.html
  src/app/core/shell/toolbar/toolbar.component.scss
  src/app/core/shell/toolbar/toolbar.component.ts
  src/assets/translations/en-US.json
  src/assets/translations/fr-FR.json
Labels: size/M

#29 [Snyk] Upgrade tslib from 2.4.0 to 2.4.1
  package-lock.json
  package.json
Labels: size/XS

#22 [Snyk] Upgrade core-js from 2.5.0 to 2.6.12
  package-lock.json
  package.json
Labels: size/XS

#20 [Snyk] Upgrade @fortawesome/free-solid-svg-icons from 5.8.2 to 5.15.4
  package-lock.json
  package.json
Labels: size/XS

#46 [SER-842] Use the roles to verify who is eligible to select a country
  src/app/core/shell/toolbar/toolbar.component.ts
Labels: size/S

#18 [Snyk] Security upgrade nginx from alpine to 1.23.1-alpine
  Dockerfile
Labels: size/XS

#49 Admin has to select a country before any other thing
  src/app/core/shell/toolbar/toolbar.component.html
Labels: size/XS
