Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2023-01, with the labels that each got.

#35 Feature/SER-1406- Add user's country Id to the field address request
  RELEASE_NOTES.md
  src/app/clients/clients.service.ts
  src/app/clients/common-resolvers/client-address-fieldconfiguration.resolver.ts
  src/app/core/authentication/credentials.model.ts
Labels: size/S

#40 Ser 1113
  RELEASE_NOTES.md
  angular.json
  src/app/hierarchy-generator.ts
  src/app/products/loan-products/create-loan-product/create-loan-product.component.html
  src/app/products/loan-products/create-loan-product/create-loan-product.component.ts
  src/app/products/loan-products/edit-loan-product/edit-loan-product.component.html
  src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-apps/loan-product-apps.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-apps/loan-product-apps.component.scss
  src/app/products/loan-products/loan-product-stepper/loan-product-apps/loan-product-apps.component.spec.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-apps/loan-product-apps.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-charges-step/loan-product-charges-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-charges-step/loan-product-charges-step.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-client-eligibility-step/loan-product-client-eligibility-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-client-eligibility-step/loan-product-client-eligibility-step.component.scss
  src/app/products/loan-products/loan-product-stepper/loan-product-client-eligibility-step/loan-product-client-eligibility-step.component.spec.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-client-eligibility-step/loan-product-client-eligibility-step.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-currency-step/loan-product-currency-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-currency-step/loan-product-currency-step.component.scss
  src/app/products/loan-products/loan-product-stepper/loan-product-currency-step/loan-product-currency-step.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.scss
  src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.spec.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.scss
  src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.ts
  src/app/products/loan-products/shared/client-eligbility/client-eligbility.component.html
  src/app/products/loan-products/shared/client-eligbility/client-eligbility.component.scss
  src/app/products/loan-products/shared/client-eligbility/client-eligbility.component.spec.ts
  src/app/products/loan-products/shared/client-eligbility/client-eligbility.component.ts
  src/app/products/loan-products/view-loan-product/view-loan-product.component.html
  src/app/products/loan-products/view-loan-product/view-loan-product.component.scss
  src/app/products/loan-products/view-loan-product/view-loan-product.component.ts
  src/app/products/products.module.ts
  src/app/products/products.service.ts
  src/app/shared/country-tree-view/country-tree-view.component.ts
  src/assets/env.js
Labels: size/XXL

#41 chore: add SonarCloud test coverage
  .github/workflows/build.yml
  .gitignore
  angular.json
  azure-pipelines.yml
  package-lock.json
  package.json
  sonar-project.properties
  src/app/core/utils/data-flattner.spec.ts
  src/app/pipes/date-format.pipe.spec.ts
  src/environments/.env.ts
  src/karma.conf.ts
Labels: size/L

#42 Ser 1278
  src/app/notifications/notifications.service.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-charges-step/loan-product-charges-step.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.scss
  src/app/products/loan-products/shared/client-eligbility/client-eligbility.component.html
  src/app/products/loan-products/shared/client-eligbility/client-eligbility.component.scss
  src/app/settings/settings.service.ts
  src/app/shared/footer/footer.component.ts
  src/app/system/configurations/business-date-tab/business-date-tab.component.ts
  src/app/system/configurations/configurations.component.ts
Labels: size/S
