Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2023-09, with the labels that each got.

#75 build: add an env var to Azure DevOps pipeline
  .github/linters/yamllint.yml
  .github/workflows/build.yml
  .github/workflows/megalinter.yml
  .gitignore
  .mega-linter.yml
  .vscode/settings.json
  azure-pipelines.yml
  sonar-project.properties
  src/environments/.env.ts
Labels: size/M

#53 Ser 1112
  RELEASE_NOTES.md
  src/app/core/shell/toolbar/toolbar.component.html
  src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.scss
  src/app/system/configure-data-fields/configure-data-fields.component.html
  src/app/system/configure-data-fields/configure-data-fields.component.scss
  src/app/system/configure-data-fields/configure-data-fields.component.spec.ts
  src/app/system/configure-data-fields/configure-data-fields.component.ts
  src/app/system/configure-data-fields/data-fields/data-fields.component.html
  src/app/system/configure-data-fields/data-fields/data-fields.component.scss
  src/app/system/configure-data-fields/data-fields/data-fields.component.spec.ts
  src/app/system/configure-data-fields/data-fields/data-fields.component.ts
  src/app/system/configure-data-fields/data-fields/manage-fields-data.resolver.ts
  src/app/system/configure-data-fields/manage-data-field.resolver.ts
  src/app/system/system-routing.module.ts
  src/app/system/system.component.html
  src/app/system/system.module.ts
  src/app/system/system.service.ts
Labels: size/XL

#74 [Snyk] Security upgrade nginx from 1.23.1-alpine to 1.25.2-alpine
  Dockerfile
Labels: size/XS
