Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2024-12, with the labels that each got.

#224 chore: Change Project version to trigger deployment on UAT
  package.json
Labels: size/XS

#206 Chore/change mifos name to fineract
  RELEASE_NOTES.md
  src/app/core/shell/sidenav/sidenav.component.html
  src/app/core/shell/sidenav/sidenav.component.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/shared/footer/footer.component.html
  src/app/shared/footer/footer.component.ts
  src/app/web-app.component.ts
  src/environments/environment.common.ts
  src/environments/environment.local.ts
  src/environments/environment.prod.ts
  src/environments/environment.qa.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
  src/index.html
Labels: size/M

#213 Ser 3281 sentry integration
  .gitignore
  RELEASE_NOTES.md
  angular.json
  package.json
  src/app/app.module.ts
  src/app/home/home.component.html
  src/assets/env.js
  src/assets/env.template.js
  src/environments/environment.local.ts
  src/environments/environment.prod.ts
  src/environments/environment.qa.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
  src/main.ts
Labels: size/L

#226 chore(SER-3309): Refactor GA deployment jobs to avoid duplicationg env variables
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: size/L

#227 Feat/ser 3259 Add payment providers external services pages
  RELEASE_NOTES.md
  package.json
  src/app/organization/offices/office.model.ts
  src/app/system/external-services/external-service.model.spec.ts
  src/app/system/external-services/external-service.model.ts
  src/app/system/external-services/external-services.component.html
  src/app/system/external-services/external-services.service.ts
  src/app/system/external-services/payment-provider/add-payment-provider/add-payment-provider.component.html
  src/app/system/external-services/payment-provider/add-payment-provider/add-payment-provider.component.scss
  src/app/system/external-services/payment-provider/add-payment-provider/add-payment-provider.component.spec.ts
  src/app/system/external-services/payment-provider/add-payment-provider/add-payment-provider.component.ts
  src/app/system/external-services/payment-provider/edit-payment-provider/edit-payment-provider.component.html
  src/app/system/external-services/payment-provider/edit-payment-provider/edit-payment-provider.component.scss
  src/app/system/external-services/payment-provider/edit-payment-provider/edit-payment-provider.component.spec.ts
  src/app/system/external-services/payment-provider/edit-payment-provider/edit-payment-provider.component.ts
  src/app/system/external-services/payment-provider/payment-provider.component.html
  src/app/system/external-services/payment-provider/payment-provider.component.scss
  src/app/system/external-services/payment-provider/payment-provider.component.spec.ts
  src/app/system/external-services/payment-provider/payment-provider.component.ts
  src/app/system/system-routing.module.ts
  src/app/system/system.module.ts
  src/app/system/system.service.ts
  src/environments/environment.local.ts
Labels: size/XL

#228 Ser 3363/clients UI translation
  .htmlhintrc
  RELEASE_NOTES.md
  angular.json
  src/app/app.module.ts
  src/app/clients/client-stepper/client-address-step/client-address-step.component.html
  src/app/clients/client-stepper/client-general-step/client-general-step.component.html
  src/app/clients/client-stepper/client-general-step/client-general-step.component.ts
  src/app/clients/client-stepper/client-preview-step/client-preview-step.component.html
  src/app/clients/client-stepper/client-preview-step/client-preview-step.component.ts
  src/app/clients/clients-view/address-tab/address-tab.component.html
  src/app/clients/clients-view/charges/charges-overview/charges-overview.component.html
  src/app/clients/clients-view/charges/client-pay-charges/client-pay-charges.component.html
  src/app/clients/clients-view/charges/view-charge/view-charge.component.html
  src/app/clients/clients-view/client-actions/accept-client-transfer/accept-client-transfer.component.html
  src/app/clients/clients-view/client-actions/activate-client/activate-client.component.html
  src/app/clients/clients-view/client-actions/add-client-charge/add-client-charge.component.html
  src/app/clients/clients-view/client-actions/client-assign-staff/client-assign-staff.component.html
  src/app/clients/clients-view/client-actions/client-screen-reports/client-screen-reports.component.html
  src/app/clients/clients-view/client-actions/close-client/close-client.component.html
  src/app/clients/clients-view/client-actions/create-self-service-user/create-self-service-user.component.html
  src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.html
  src/app/clients/clients-view/client-actions/reject-client-transfer/reject-client-transfer.component.html
  src/app/clients/clients-view/client-actions/reject-client/reject-client.component.html
  src/app/clients/clients-view/client-actions/take-survey/take-survey.component.html
  src/app/clients/clients-view/client-actions/transfer-client/transfer-client.component.html
  src/app/clients/clients-view/client-actions/undo-client-rejection/undo-client-rejection.component.html
  src/app/clients/clients-view/client-actions/undo-client-transfer/undo-client-transfer.component.html
  src/app/clients/clients-view/client-actions/update-client-savings-account/update-client-savings-account.component.html
  src/app/clients/clients-view/client-actions/view-survey/view-survey.component.html
  src/app/clients/clients-view/client-actions/withdraw-client/withdraw-client.component.html
  src/app/clients/clients-view/clients-view.component.html
  src/app/clients/clients-view/custom-dialogs/capture-image-dialog/capture-image-dialog.component.html
  src/app/clients/clients-view/custom-dialogs/delete-signature-dialog/delete-signature-dialog.component.html
  src/app/clients/clients-view/custom-dialogs/edit-notes-dialog/edit-notes-dialog.component.html
  src/app/clients/clients-view/custom-dialogs/unassign-staff-dialog/unassign-staff-dialog.component.html
  src/app/clients/clients-view/custom-dialogs/upload-document-dialog/upload-document-dialog.component.html
  src/app/clients/clients-view/custom-dialogs/upload-image-dialog/upload-image-dialog.component.html
  src/app/clients/clients-view/custom-dialogs/upload-signature-dialog/upload-signature-dialog.component.html
  src/app/clients/clients-view/custom-dialogs/view-signature-dialog/view-signature-dialog.component.html
  src/app/clients/clients-view/general-tab/general-tab.component.html
  src/app/clients/clients-view/general-tab/general-tab.component.ts
  src/app/clients/clients-view/identities-tab/identities-tab.component.html
  src/app/clients/clients.component.html
  src/app/clients/clients.component.ts
  src/app/clients/create-client/create-client.component.html
  src/app/clients/edit-client/edit-client.component.html
  src/app/clients/edit-client/edit-client.component.ts
  src/app/core/core.module.ts
  src/app/pipes/pipes.module.ts
  src/app/pipes/translate.pipe.ts
  src/app/pipes/truncate-text.pipe.ts
  src/app/pipes/yesno.pipe.ts
  src/app/shared/shared.module.ts
  src/assets/translations/en-US.json
  src/assets/translations/fr-FR.json
Labels: size/XXL
