Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2024-05, with the labels that each got.

#102 Ser 2510/show officehierachy name
  .vscode/settings.json
  RELEASE_NOTES.md
  src/app/clients/client-stepper/client-general-step/client-general-step.component.html
  src/app/clients/client-stepper/client-general-step/client-general-step.component.scss
  src/app/clients/clients-view/client-actions/transfer-client/transfer-client.component.html
  src/app/clients/clients-view/client-actions/transfer-client/transfer-client.component.scss
  src/app/clients/clients-view/clients-view.component.html
  src/app/core/shell/sidenav/sidenav.component.html
  src/app/core/shell/toolbar/toolbar.component.html
  src/app/groups/create-group/create-group.component.html
  src/app/groups/create-group/create-group.component.scss
  src/app/organization/offices/combine-office/combine-office.component.html
  src/app/organization/offices/combine-office/combine-office.component.scss
  src/app/organization/offices/create-office/create-office.component.scss
  src/app/organization/offices/edit-office/edit-office.component.html
  src/app/organization/offices/edit-office/edit-office.component.scss
  src/app/organization/offices/split-office/split-office.component.html
  src/app/organization/offices/split-office/split-office.component.scss
  src/app/users/create-user/create-user.component.scss
Labels: size/L

#103 Ser 2034/return clients for country
  Dockerfile
  RELEASE_NOTES.md
  src/app/clients/clients.datasource.ts
  src/app/clients/clients.service.ts
  src/app/groups/groups.datasource.ts
  src/app/groups/groups.service.ts
  src/app/products/loan-products/loan-products.resolver.ts
  src/app/products/products.service.ts
Labels: size/XL

#105 feat: SER-2486/Select country-loan product when creating savings account
  RELEASE_NOTES.md
  src/app/products/saving-products/saving-product-stepper/saving-product-details-step/saving-product-details-step.component.html
  src/app/products/saving-products/saving-product-stepper/saving-product-details-step/saving-product-details-step.component.ts
Labels: size/L

#106 feat: Update displayed columns in clients and loan products components
  RELEASE_NOTES.md
  src/.prettierrc
  src/app/clients/clients.component.html
  src/app/clients/clients.component.ts
  src/app/groups/groups.component.html
  src/app/groups/groups.component.ts
  src/app/products/loan-products/loan-products.component.html
  src/app/products/loan-products/loan-products.component.ts
  src/app/products/loan-products/view-loan-product/view-loan-product.component.html
Labels: size/XXL

#107 Ser1561/office view fixes
  RELEASE_NOTES.md
  src/app/organization/offices/offices.component.ts
  src/app/organization/offices/view-office/general-tab/general-tab.component.html
  src/app/shared/office-tree-view/office-tree-node.ts
  src/app/shared/office-tree-view/office-tree-view.component.html
  src/app/shared/office-tree-view/office-tree-view.component.ts
Labels: size/L

#108 feat: Include Phone Number in Repayment Transaction Details
  RELEASE_NOTES.md
  src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.html
Labels: size/M

#109 Add support for OU level config - SER-2523
  RELEASE_NOTES.md
  src/app/organization/organization.service.ts
  src/app/system/configurations/global-configurations-tab/clone-configuration/clone-configuration.component.html
  src/app/system/configurations/global-configurations-tab/clone-configuration/clone-configuration.component.ts
  src/app/system/configurations/global-configurations-tab/edit-configuration/edit-configuration.component.html
  src/app/system/configurations/global-configurations-tab/edit-configuration/edit-configuration.component.ts
  src/app/system/configurations/global-configurations-tab/global-configuration.resolver.ts
  src/app/system/configurations/global-configurations-tab/global-configurations-tab.component.html
  src/app/system/configurations/global-configurations-tab/global-configurations-tab.component.ts
Labels: size/L

#110 Azure Pipeline: Add conditions to building artifacts
  azure-pipelines.yml
Labels: size/M

#111 Disabling validating linting on all the codebase for now as we have a lot of legacy code
  azure-pipelines.yml
Labels: size/XS

#113 SER_2549/Implement Loan Account Bulk Upload in Fineract v2
  .mega-linter.yml
  RELEASE_NOTES.md
  src/app/organization/bulk-import/bulk-import.component.html
  src/app/organization/bulk-import/view-bulk-import/view-bulk-import.component.ts
  src/app/system/manage-hooks/add-event-dialog/add-event-dialog.component.ts
Labels: size/L

#115 Add required steps to deploy v2 on Azure
  azure-pipelines.yml
  values.yaml
Labels: size/M
