Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2024-09, with the labels that each got.

#191 SER-2881 Re-enable configuration of the currency multiple from direct…
  RELEASE_NOTES.md
  src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.ts
Labels: size/S

#193 SER-3008 load OUs up to configured OU level if configured
  RELEASE_NOTES.md
  src/app/organization/organization.service.ts
  src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.ts
  src/app/products/loan-products/view-loan-product/view-loan-product.component.ts
Labels: size/S

#196 chore(SER-2803): Add configs for automatically triggering deployment
  .github/actions/dispatch/action.yml
  .github/workflows/build.yml
  README.md
  RELEASE_NOTES.md
Labels: size/M

#198 chore(SER-2803): Add checkout step in deploy job
  .github/workflows/build.yml
Labels: size/XS
