Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2024-04, with the labels that each got.

#95 SER-2440 - Revise the country selection option
  RELEASE_NOTES.md
  env.sample
  src/app/core/shell/toolbar/toolbar.component.html
  src/app/core/shell/toolbar/toolbar.component.ts
  src/assets/env.js
  src/assets/env.template.js
  src/environments/environment.local.ts
  src/environments/environment.prod.ts
  src/environments/environment.qa.ts
  src/environments/environment.ts
Labels: size/M

#94 Fix view client details
  RELEASE_NOTES.md
  src/app/clients/clients-routing.module.ts
  src/app/clients/clients-view/clients-view.component.html
  src/app/clients/clients-view/general-tab/general-tab.component.html
  src/app/clients/clients-view/general-tab/general-tab.component.ts
Labels: size/L

#96 Ser 2446/dropdown update
  RELEASE_NOTES.md
  package-lock.json
  package.json
  src/app/clients/client-stepper/client-general-step/client-general-step.component.html
  src/app/clients/clients-routing.module.ts
  src/app/clients/clients-view/clients-view.component.html
  src/app/clients/clients-view/clients-view.component.ts
  src/app/clients/clients-view/general-tab/general-tab.component.html
  src/app/clients/clients-view/general-tab/general-tab.component.ts
  src/app/groups/create-group/create-group.component.html
  src/app/groups/groups-routing.module.ts
  src/app/groups/groups-view/general-tab/general-tab.component.html
  src/app/groups/groups-view/general-tab/general-tab.component.ts
  src/app/groups/groups-view/groups-view.component.html
  src/app/shared/shared.module.ts
  src/assets/env.js
  src/environments/environment.test.ts
  src/theme/custom/denim-yellowgreen.scss
Labels: size/XXL

#98 Ser 2458/replace matselect filter
  RELEASE_NOTES.md
  package-lock.json
  package.json
  src/app/clients/clients-view/client-actions/transfer-client/transfer-client.component.html
  src/app/core/http/http.service.ts
  src/app/organization/bulk-import/bulk-repayment-download/bulk-repayment-download.component.html
  src/app/organization/bulk-import/view-bulk-import/view-bulk-import.component.html
  src/app/organization/currencies/create-currencies/create-currencies.component.html
  src/app/organization/offices/combine-office/combine-office.component.html
  src/app/organization/offices/combine-office/combine-office.component.scss
  src/app/organization/offices/combine-office/combine-office.component.ts
  src/app/organization/offices/create-office/create-office.component.html
  src/app/organization/offices/edit-office/edit-office.component.html
  src/app/organization/offices/offices.component.html
  src/app/organization/offices/offices.component.scss
  src/app/organization/offices/offices.component.ts
  src/app/organization/offices/split-office/split-office.component.html
  src/app/organization/offices/split-office/split-office.component.ts
  src/app/organization/rural-outlet/create-outlet/create-outlet.component.html
  src/app/organization/rural-outlet/create-outlet/create-outlet.component.ts
  src/app/products/charges/create-charge/create-charge.component.html
  src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.html
  src/app/products/loan-product-allocation-setting/loan-product-allocation/loan-product-allocation.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.ts
  src/app/shared/material.module.ts
  src/app/system/configurations/global-configurations-tab/clone-configuration/clone-configuration.component.html
  src/app/system/configure-data-fields/configure-data-fields.component.html
  src/app/system/configure-data-fields/data-fields/data-fields.component.html
Labels: size/XXL
