Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2024-06, with the labels that each got.

#116 update hooks interface to accomodate Rabbit MQ template
  RELEASE_NOTES.md
  src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.html
  src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.ts
  src/app/clients/common-resolvers/client-actions.resolver.ts
  src/app/core/http/api-prefix.interceptor.ts
  src/app/organization/offices/create-office/create-office.component.html
  src/app/system/manage-hooks/create-hook/create-hook.component.html
  src/app/system/manage-hooks/create-hook/create-hook.component.ts
  src/app/system/manage-hooks/edit-hook/edit-hook.component.html
  src/app/system/manage-hooks/edit-hook/edit-hook.component.ts
  src/app/system/manage-hooks/view-hook/view-hook.component.html
Labels: size/XL

#117 chore: Update getClientData method to include credit score data for c…
  RELEASE_NOTES.md
  src/app/clients/clients-view/clients-view.component.html
  src/app/clients/clients-view/identities-tab/identities-tab.component.html
  src/app/clients/clients-view/identities-tab/identities-tab.component.ts
  src/app/clients/clients.datasource.ts
  src/app/clients/clients.service.ts
  src/app/clients/common-resolvers/client-view.resolver.ts
Labels: size/L

#118 fix [SER-2600] - Fix edit loan product failing due to unsupported fields being submitted
  RELEASE_NOTES.md
  src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.ts
Labels: size/S

#119 Remove templateForTermsAndConditions if it's empty
  src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts
Labels: size/XS

#120 feat: Remove staff id from payload when creating users
  RELEASE_NOTES.md
  src/app/users/create-user/create-user.component.ts
  src/environments/environment.prod.ts
Labels: size/M

#121 fix fineract api url
  src/environments/environment.prod.ts
Labels: size/XS

#122 fix SER-2600 Fix terms and conditions not being populated correctly on create & edit loan product pages
  RELEASE_NOTES.md
  src/app/products/loan-products/create-loan-product/create-loan-product.component.html
  src/app/products/loan-products/create-loan-product/create-loan-product.component.ts
  src/app/products/loan-products/edit-loan-product/edit-loan-product.component.html
  src/app/products/loan-products/edit-loan-product/edit-loan-product.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-apps/loan-product-apps.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
  src/app/products/products.service.ts
Labels: size/M

#123 fix SER-2600 - User creation: Set sendPasswordToEmail to always be false
  RELEASE_NOTES.md
  src/app/users/create-user/create-user.component.ts
Labels: size/XS

#124 fix SER-2600: Fix adding member to group due to initialization bug
  RELEASE_NOTES.md
  src/app/groups/groups-view/group-actions/manage-group-members/manage-group-members.component.ts
Labels: size/XS

#125 feat: Show overpaid amount on account summary and remove interests su…
  .htmlhintrc
  RELEASE_NOTES.md
  src/app/loans/loans-view/loans-view.component.html
  src/app/loans/loans-view/transactions-tab/transactions-tab.component.html
  src/app/loans/loans-view/transactions-tab/transactions-tab.component.ts
Labels: size/XL

#112 [Snyk] Upgrade zone.js from 0.11.6 to 0.14.5
  package-lock.json
  package.json
Labels: size/XS

#126 feat: change input type from number to tel
  RELEASE_NOTES.md
  package.json
  src/app/clients/client-stepper/client-general-step/client-general-step.component.html
  src/app/clients/edit-client/edit-client.component.html
Labels: size/M

#129 Ser 2686/fix hook edit
  RELEASE_NOTES.md
  src/app/core/authentication/authentication.service.ts
  src/app/core/shell/sidenav/sidenav.component.ts
  src/app/notifications/notifications.service.ts
  src/app/organization/offices/create-office/create-office.component.ts
  src/app/organization/offices/edit-office/edit-office.component.ts
  src/app/shared/office-tree-view/office-tree-view.component.html
  src/app/system/manage-hooks/edit-hook/edit-hook.component.ts
Labels: size/L

#130 fix: fix credit score label data, ability to activate, deactivate and…
  RELEASE_NOTES.md
  src/app/clients/clients-view/clients-view.component.html
  src/app/organization/offices/view-office/general-tab/general-tab.component.html
  src/app/organization/offices/view-office/general-tab/general-tab.component.ts
  src/app/organization/organization.service.ts
Labels: size/L

#133 feat: show activate button when a group has been deactivated
  RELEASE_NOTES.md
  src/app/groups/groups-view/groups-view.component.html
Labels: size/L

#132 feat: show currency and loan product name when displaying savings pro…
  RELEASE_NOTES.md
  docker-compose.yml
  src/app/products/saving-products/saving-product-stepper/saving-product-details-step/saving-product-details-step.component.ts
  src/app/products/saving-products/saving-products.component.html
  src/app/products/saving-products/saving-products.component.ts
  src/app/products/saving-products/view-saving-product/view-saving-product.component.html
  src/assets/env.js
  src/assets/env.template.js
  src/environments/environment.local.ts
  src/environments/environment.prod.ts
  src/environments/environment.qa.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: size/L

#134 feat: fix view client signature and click group name from client view
  RELEASE_NOTES.md
  src/app/clients/clients-view/clients-view.component.html
  src/app/clients/clients-view/custom-dialogs/view-signature-dialog/view-signature-dialog.component.ts
Labels: size/S

#135 feat: show proper error message when error status is 400
  RELEASE_NOTES.md
  src/app/clients/clients-view/clients-view.component.html
  src/app/core/http/error-handler.interceptor.ts
  src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.ts
Labels: size/L

#136 feat SER-2537: Add country link to SMS campaigns
  RELEASE_NOTES.md
  src/app/organization/sms-campaigns/edit-campaign/edit-campaign.component.html
  src/app/organization/sms-campaigns/sms-campaign-stepper/campaign-preview-step/campaign-preview-step.component.html
  src/app/organization/sms-campaigns/sms-campaign-stepper/edit-sms-campaign-step/edit-business-rule-parameters/edit-business-rule-parameters.component.ts
  src/app/organization/sms-campaigns/sms-campaign-stepper/edit-sms-campaign-step/edit-sms-campaign-step.component.html
  src/app/organization/sms-campaigns/sms-campaign-stepper/edit-sms-campaign-step/edit-sms-campaign-step.component.ts
  src/app/organization/sms-campaigns/sms-campaign-stepper/sms-campaign-step/business-rule-parameters/business-rule-parameters.component.ts
  src/app/organization/sms-campaigns/sms-campaign-stepper/sms-campaign-step/sms-campaign-step.component.html
  src/app/organization/sms-campaigns/sms-campaign-stepper/sms-campaign-step/sms-campaign-step.component.ts
  src/app/organization/sms-campaigns/sms-campaigns.component.html
  src/app/organization/sms-campaigns/sms-campaigns.component.ts
  src/app/organization/sms-campaigns/view-campaign/view-campaign.component.html
  src/app/reports/reports.service.ts
Labels: size/M

#137 fix: fix navigations in the group view interface
  RELEASE_NOTES.md
  src/app/groups/groups-view/general-tab/general-tab.component.html
  src/app/groups/groups-view/groups-view.component.html
Labels: size/S

#104 Feature | SER-2519 install and configure Matomo web analytics
  .gitignore
  package.json
  src/app/app.module.ts
  src/app/clients/client-stepper/client-address-step/client-address-step.component.ts
  src/app/clients/client-stepper/client-family-members-step/client-family-members-step.component.ts
  src/app/clients/client-stepper/client-general-step/client-general-step.component.ts
  src/app/clients/clients-view/address-tab/address-tab.component.ts
  src/app/clients/clients-view/charges/charges-overview/charges-overview.component.ts
  src/app/clients/clients-view/charges/client-pay-charges/client-pay-charges.component.ts
  src/app/clients/clients-view/charges/view-charge/view-charge.component.ts
  src/app/clients/clients-view/client-actions/accept-client-transfer/accept-client-transfer.component.ts
  src/app/clients/clients-view/client-actions/activate-client/activate-client.component.ts
  src/app/clients/clients-view/client-actions/add-client-charge/add-client-charge.component.ts
  src/app/clients/clients-view/client-actions/client-assign-staff/client-assign-staff.component.ts
  src/app/clients/clients-view/client-actions/client-screen-reports/client-screen-reports.component.ts
  src/app/clients/clients-view/client-actions/close-client/close-client.component.ts
  src/app/clients/clients-view/client-actions/create-self-service-user/create-self-service-user.component.ts
  src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.ts
  src/app/clients/clients-view/client-actions/reject-client-transfer/reject-client-transfer.component.ts
  src/app/clients/clients-view/client-actions/reject-client/reject-client.component.ts
  src/app/clients/clients-view/client-actions/take-survey/take-survey.component.ts
  src/app/clients/clients-view/client-actions/transfer-client/transfer-client.component.ts
  src/app/clients/clients-view/client-actions/undo-client-rejection/undo-client-rejection.component.ts
  src/app/clients/clients-view/client-actions/undo-client-transfer/undo-client-transfer.component.ts
  src/app/clients/clients-view/client-actions/update-client-savings-account/update-client-savings-account.component.ts
  src/app/clients/clients-view/client-actions/view-survey/view-survey.component.ts
  src/app/clients/clients-view/client-actions/withdraw-client/withdraw-client.component.ts
  src/app/clients/clients-view/clients-view.component.ts
  src/app/clients/clients-view/custom-dialogs/capture-image-dialog/capture-image-dialog.component.ts
  src/app/clients/clients-view/custom-dialogs/delete-signature-dialog/delete-signature-dialog.component.ts
  src/app/clients/clients-view/custom-dialogs/edit-notes-dialog/edit-notes-dialog.component.ts
  src/app/clients/clients-view/custom-dialogs/unassign-staff-dialog/unassign-staff-dialog.component.ts
  src/app/clients/clients-view/custom-dialogs/upload-document-dialog/upload-document-dialog.component.ts
  src/app/clients/clients-view/custom-dialogs/upload-image-dialog/upload-image-dialog.component.ts
  src/app/clients/clients-view/custom-dialogs/upload-signature-dialog/upload-signature-dialog.component.ts
  src/app/clients/clients-view/custom-dialogs/view-signature-dialog/view-signature-dialog.component.ts
  src/app/clients/clients-view/datatable-tab/datatable-tab.component.ts
  src/app/clients/clients-view/documents-tab/documents-tab.component.ts
  src/app/clients/clients-view/family-members-tab/family-members-tab.component.ts
  src/app/clients/clients-view/general-tab/general-tab.component.ts
  src/app/clients/clients-view/identities-tab/identities-tab.component.ts
  src/app/clients/clients-view/notes-tab/notes-tab.component.ts
  src/app/clients/clients.component.ts
  src/app/clients/create-client/create-client.component.ts
  src/app/clients/edit-client/edit-client.component.ts
  src/app/web-app.component.ts
  src/environments/.env.ts
  src/environments/environment.local.ts
  src/environments/environment.prod.ts
  src/environments/environment.qa.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: size/XXL

#139 Lint-improvements
  .github/workflows/megalinter.yml
  .mega-linter.yml
  yamllint.yml
Labels: size/L

#138 Validate OTP when updating client mobile number - SER-2507
  RELEASE_NOTES.md
  package-lock.json
  package.json
  src/app/clients/client-otp-dialog/client-otp-dialog.component.html
  src/app/clients/client-otp-dialog/client-otp-dialog.component.scss
  src/app/clients/client-otp-dialog/client-otp-dialog.component.spec.ts
  src/app/clients/client-otp-dialog/client-otp-dialog.component.ts
  src/app/clients/clients.module.ts
  src/app/clients/clients.service.ts
  src/app/clients/edit-client/edit-client.component.html
  src/app/clients/edit-client/edit-client.component.ts
  src/app/shared/shared.module.ts
  src/app/system/system.service.ts
Labels: size/L

#140 feat SER-2537 Give ability to select All in SMS campaign Office dropdown
  docker-compose.yml
  src/app/organization/sms-campaigns/sms-campaign-stepper/edit-sms-campaign-step/edit-business-rule-parameters/edit-business-rule-parameters.component.ts
  src/app/organization/sms-campaigns/sms-campaign-stepper/edit-sms-campaign-step/edit-sms-campaign-step.component.html
  src/app/organization/sms-campaigns/sms-campaign-stepper/sms-campaign-step/business-rule-parameters/business-rule-parameters.component.ts
  src/app/reports/run-report/run-report.component.ts
Labels: size/S
