Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2024-07, with the labels that each got.

#141 fix: Remove templates link to organization
  RELEASE_NOTES.md
  src/app/core/shell/toolbar/toolbar.component.html
  src/app/organization/organization.component.html
Labels: size/M

#142 feat: Add conditional rendering for admin menu button
  src/app/clients/clients-view/clients-view.component.html
  src/app/clients/clients.component.html
  src/app/core/shell/toolbar/toolbar.component.html
  src/app/loans/loans-view/transactions-tab/transactions-tab.component.html
  src/app/loans/loans-view/transactions-tab/transactions-tab.component.ts
Labels: size/S

#143 feat SER-2803 Add Github actions
  .deleted-azure-pipelines.yml
  .github/workflows/build.yml
Labels: size/L

#144 feat SER-2745 Fix Bulk imports file naming
  .github/workflows/build.yml
  RELEASE_NOTES.md
  deployment/values.yaml
  src/app/organization/bulk-import/bulk-repayment-download/bulk-repayment-download.component.ts
  src/app/organization/bulk-import/view-bulk-import/view-bulk-import.component.ts
  src/app/organization/organization.service.ts
Labels: size/M

#145 feat SER-2803: Add use latest image tag
  .github/workflows/build.yml
Labels: size/XS

#146 feat: Allow override of OCR checks if a user has the SKIP_VERIFICATIO…
  RELEASE_NOTES.md
  src/app/clients/clients-view/client-actions/activate-client/activate-client.component.html
  src/app/clients/clients-view/client-actions/activate-client/activate-client.component.ts
  src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.html
  src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.ts
Labels: size/M

#149 feat (SER-1909) - Display necessary fields for the loan product page
  src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
Labels: size/S

#155 fix: Update search and filter labels in clients component
  RELEASE_NOTES.md
  src/app/clients/clients.component.html
  src/app/system/manage-scheduler-jobs/manage-scheduler-jobs.component.html
  src/assets/env.js
  src/assets/env.template.js
Labels: size/L

#157 Remove loan payment button from the UI
  RELEASE_NOTES.md
  src/app/clients/clients-view/general-tab/general-tab.component.html
  src/app/loans/loans-view/loan-accounts-button-config.ts
  src/app/loans/loans-view/loans-view.component.ts
Labels: size/M

#158 Update the project version to 1.3.0
  RELEASE_NOTES.md
  package.json
Labels: size/XS

#159 Merge develop into main
  RELEASE_NOTES.md
  package.json
  src/app/clients/clients-view/client-actions/activate-client/activate-client.component.html
  src/app/clients/clients-view/client-actions/activate-client/activate-client.component.ts
  src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.html
  src/app/clients/clients-view/client-actions/reactivate-client/reactivate-client.component.ts
  src/app/clients/clients-view/general-tab/general-tab.component.html
  src/app/clients/clients.component.html
  src/app/loans/loans-view/loan-accounts-button-config.ts
  src/app/loans/loans-view/loans-view.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.ts
  src/app/system/manage-scheduler-jobs/manage-scheduler-jobs.component.html
  src/assets/env.js
  src/assets/env.template.js
Labels: size/L

#164 SER-2854 Editing a loan product leads to loss of attached charges
  RELEASE_NOTES.md
  src/app/products/loan-products/loan-product-stepper/loan-product-charges-step/loan-product-charges-step.component.ts
Labels: size/XS

#154 feat(SER-2859) Add a new field(string value) on the config page
  RELEASE_NOTES.md
  src/app/system/configurations/global-configurations-tab/clone-configuration/clone-configuration.component.html
  src/app/system/configurations/global-configurations-tab/clone-configuration/clone-configuration.component.ts
  src/app/system/configurations/global-configurations-tab/edit-configuration/edit-configuration.component.html
  src/app/system/configurations/global-configurations-tab/edit-configuration/edit-configuration.component.ts
  src/app/system/configurations/global-configurations-tab/global-configurations-tab.component.html
  src/app/system/configurations/global-configurations-tab/global-configurations-tab.component.scss
  src/app/system/configurations/global-configurations-tab/global-configurations-tab.component.ts
Labels: size/M

#163 feat: Show only active offices when creating clients and load only ac…
  RELEASE_NOTES.md
  package-lock.json
  src/app/clients/client-stepper/client-general-step/client-general-step.component.ts
  src/app/organization/organization.service.ts
Labels: size/M

#165 Prepare 1.3.1 deployment
  RELEASE_NOTES.md
  package.json
Labels: size/XS

#166 Merge develop into main
  RELEASE_NOTES.md
  package-lock.json
  package.json
  src/app/clients/client-stepper/client-general-step/client-general-step.component.ts
  src/app/organization/organization.service.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-charges-step/loan-product-charges-step.component.ts
  src/app/system/configurations/global-configurations-tab/clone-configuration/clone-configuration.component.html
  src/app/system/configurations/global-configurations-tab/clone-configuration/clone-configuration.component.ts
  src/app/system/configurations/global-configurations-tab/edit-configuration/edit-configuration.component.html
  src/app/system/configurations/global-configurations-tab/edit-configuration/edit-configuration.component.ts
  src/app/system/configurations/global-configurations-tab/global-configurations-tab.component.html
  src/app/system/configurations/global-configurations-tab/global-configurations-tab.component.scss
  src/app/system/configurations/global-configurations-tab/global-configurations-tab.component.ts
Labels: size/M
