Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2024-08, with the labels that each got.

#168 feat: Show or hide some menus based on user permissions
  RELEASE_NOTES.md
  src/app/clients/clients-view/clients-view.component.html
  src/app/organization/organization.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html
Labels: size/M

#169 chore: Prepare Release of 1.3.2
  .github/workflows/build.yml
  RELEASE_NOTES.md
  package.json
Labels: size/S

#170 Merge develop into main branch for Release 1.3.2
  .github/workflows/build.yml
  RELEASE_NOTES.md
  package.json
  src/app/clients/clients-view/clients-view.component.html
  src/app/organization/organization.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-settings-step/loan-product-settings-step.component.html
Labels: size/M

#182 feat: Add client's date of birth to client profile view
  RELEASE_NOTES.md
  package.json
  src/app/clients/clients-view/clients-view.component.html
Labels: size/S

#184 SER-2902 Disable loan submit button for 5 seconds to avoid double clicks
  RELEASE_NOTES.md
  docker-compose.yml
  src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.html
  src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.ts
  src/assets/env.js
  src/assets/env.template.js
  src/environments/environment.local.ts
  src/environments/environment.prod.ts
  src/environments/environment.qa.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: size/M

#185 feat: SER-2664 show only client eligible lp
  RELEASE_NOTES.md
  src/app/loans/loans.service.ts
Labels: size/XS

#188 Merge develop into main
  RELEASE_NOTES.md
  docker-compose.yml
  package.json
  src/app/clients/clients-view/clients-view.component.html
  src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.html
  src/app/loans/loans-account-stepper/loans-account-preview-step/loans-account-preview-step.component.ts
  src/app/loans/loans.service.ts
  src/app/system/configurations/global-configurations-tab/clone-configuration/clone-configuration.component.html
  src/app/system/configurations/global-configurations-tab/clone-configuration/clone-configuration.component.ts
  src/app/system/configurations/global-configurations-tab/edit-configuration/edit-configuration.component.html
  src/app/system/configurations/global-configurations-tab/global-configurations-tab.component.html
  src/app/system/configurations/global-configurations-tab/global-configurations-tab.component.ts
  src/assets/env.js
  src/assets/env.template.js
  src/environments/environment.local.ts
  src/environments/environment.prod.ts
  src/environments/environment.qa.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: size/M
