Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2024-11, with the labels that each got.

#209 SER-2543 (Umuganda) - Implement the User Agent
  RELEASE_NOTES.md
  src/app/core/core.module.ts
  src/app/core/user-agent/user-agent.interceptor.ts
  src/app/core/user-agent/user-agent.service.spec.ts
  src/app/core/user-agent/user-agent.service.ts
  src/assets/env.js
  src/environments/environment.local.ts
  src/environments/environment.prod.ts
  src/environments/environment.qa.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: size/M

#208 feat: update link colors for group and office labels in client detail…
  RELEASE_NOTES.md
  src/app/clients/clients-view/clients-view.component.html
  src/app/clients/clients-view/clients-view.component.scss
Labels: size/S

#210 Feat/SER-3203 force country support on sms campaigns
  RELEASE_NOTES.md
  package.json
  src/app/organization/organization.service.ts
  src/app/organization/sms-campaigns/common-resolvers/sms-campaign-template.resolver.ts
  src/app/organization/sms-campaigns/sms-campaign-stepper/edit-sms-campaign-step/edit-sms-campaign-step.component.ts
  src/app/organization/sms-campaigns/sms-campaign-stepper/sms-campaign-step/sms-campaign-step.component.html
  src/app/organization/sms-campaigns/sms-campaign-stepper/sms-campaign-step/sms-campaign-step.component.ts
Labels: size/M

#211 Update the config name used to check if OTP validation should be initiated - SER-3214
  RELEASE_NOTES.md
  src/app/clients/edit-client/edit-client.component.ts
Labels: size/XS

#212 Fix/SER-3088 : Filter sms campaigns list by country & Add env var for Keycloak Token URL
  .github/workflows/megalinter.yml
  RELEASE_NOTES.md
  docker-compose.yml
  src/app/clients/clients.component.ts
  src/app/clients/clients.datasource.ts
  src/app/organization/organization.service.ts
  src/app/products/saving-products/saving-product-stepper/saving-product-details-step/saving-product-details-step.component.ts
  src/app/settings/settings.service.ts
  src/assets/env.js
  src/assets/env.template.js
  src/environments/environment.local.ts
  src/environments/environment.prod.ts
  src/environments/environment.qa.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: size/M

#214 Chore/add keycloak token env variable
  .github/actions/helm_fineract_frontend/action.yml
  .github/workflows/build.yml
  .github/workflows/megalinter.yml
  docker-compose.yml
  src/assets/env.js
  src/assets/env.template.js
  src/environments/environment.local.ts
  src/environments/environment.prod.ts
  src/environments/environment.qa.ts
  src/environments/environment.test.ts
  src/environments/environment.ts
Labels: size/M

#218 HOTFIX 1.3.4.2 - Loan Product UI Fixes for Short Name, Channels, and Client Eligibility Validation - SER-3241
  RELEASE_NOTES.md
  package.json
  src/app/products/loan-products/loan-product-stepper/loan-product-apps/loan-product-apps.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-apps/loan-product-apps.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-client-eligibility-step/loan-product-client-eligibility-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-client-eligibility-step/loan-product-client-eligibility-step.component.scss
  src/app/products/loan-products/loan-product-stepper/loan-product-client-eligibility-step/loan-product-client-eligibility-step.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-details-step/loan-product-details-step.component.html
Labels: size/M

#216 chore: Add dependency on deployment step
  .github/workflows/build.yml
Labels: size/XS

#217 Chore/add deployment configs on master branch
  .github/actions/helm_fineract_frontend/action.yml
  .github/workflows/build.yml
Labels: size/L

#219 HOTFIX - Check explicitly for null and undefined client eligibility values
  src/app/products/loan-products/loan-product-stepper/loan-product-client-eligibility-step/loan-product-client-eligibility-step.component.ts
Labels: size/XS

#221 chore: Fix UAT deployment to add dependency on build & sonarcloud jobs
  .github/workflows/build.yml
Labels: size/XS
