Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2025-07, with the labels that each got.

#256 Feature/cp 3646 loan charges with decimal values should optionally be rounded down to the nearest whole number
  RELEASE_NOTES.md
  src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.html
  src/app/products/loan-products/loan-product-stepper/loan-product-organization-unit-step/loan-product-organization-unit-step.component.ts
  src/app/products/loan-products/loan-product-stepper/loan-product-preview-step/loan-product-preview-step.component.html
  src/app/products/loan-products/view-loan-product/view-loan-product.component.html
  src/assets/translations/en-US.json
  src/assets/translations/fr-FR.json
Labels: size/S, untested

#258 chore(CP-1689): Configure Real User Monitoring with Elastic APM
  RELEASE_NOTES.md
  package.json
  src/app/app.module.ts
  src/app/core/core.module.ts
  src/app/core/init/elastic-apm/apm.init.service.spec.ts
  src/app/core/init/elastic-apm/apm.init.service.ts
  src/environments/environment.common.ts
  src/environments/environment.local.ts
  src/environments/environment.ts
Labels: size/L, untested

#254 Feature/CP-3554 - Automate virtual account creation for squadCo
  RELEASE_NOTES.md
  src/app/system/external-services/external-service.model.ts
  src/app/system/external-services/payment-provider/add-payment-provider/add-payment-provider.component.html
  src/app/system/external-services/payment-provider/add-payment-provider/add-payment-provider.component.ts
  src/app/system/external-services/payment-provider/edit-payment-provider/edit-payment-provider.component.html
  src/app/system/external-services/payment-provider/edit-payment-provider/edit-payment-provider.component.ts
Labels: size/L, untested

#264 Chore/feat CP-1689: cherry pick rum configs in release v1.3.8.1 branch
  .github/actions/helm_fineract_frontend/action.yml
  .github/workflows/build.yml
  RELEASE_NOTES.md
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/core/core.module.ts
  src/app/core/init/elastic-apm/apm.init.service.spec.ts
  src/app/core/init/elastic-apm/apm.init.service.ts
  src/assets/env.js
  src/assets/env.template.js
  src/environments/environment.common.ts
  src/environments/environment.local.ts
  src/environments/environment.ts
Labels: size/L

#267 CP-3734 show office hierarch path
  RELEASE_NOTES.md
  package.json
  src/app/clients/clients.service.ts
  src/app/groups/groups.service.ts
  src/app/organization/organization.service.ts
  src/assets/translations/en-US.json
  src/assets/translations/fr-FR.json
  src/assets/translations/sw-KE.json
Labels: size/L

#272 Cp 3722 hide taken input on client eligibility on loan product
  RELEASE_NOTES.md
  src/app/products/loan-products/loan-product-stepper/loan-product-client-eligibility-step/loan-product-client-eligibility-step.component.html
  src/app/products/loan-products/shared/client-eligbility/client-eligbility.component.html
Labels: size/S, untested
