Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2025-02, with the labels that each got.

#234 Feat/ser 3313 bulk account transfer
  RELEASE_NOTES.md
  src/app/organization/bulk-import/bulk-import.component.html
  src/app/organization/bulk-import/view-bulk-import/bulk-imports.ts
Labels: size/S

#235 Standardize Deployment Workflows and Update GitHub Actions for fineract-frontend-v2
  .github/CODEOWNERS
  .github/actions/helm_fineract_frontend/action.yml
  .github/workflows/build.yml
  .github/workflows/create-docker-hub-image.yml
  .github/workflows/deploy.yml
  .github/workflows/megalinter.yml
  .mega-linter.yml
  .yamllint.yml
  Dockerfile
  docker-compose.yml
Labels: size/L

#236 Enhance configuration and deployment processes
  .github/actions/helm_fineract_frontend/action.yml
  .github/workflows/build.yml
Labels: size/M
