Repository one-acre-fund/fineract-frontend-v2, pull requests merged in 2025-04, with the labels that each got.

#240 Merge in develop
  .github/CODEOWNERS
  .github/actions/helm_fineract_frontend/action.yml
  .github/workflows/build.yml
  .github/workflows/create-docker-hub-image.yml
  .github/workflows/deploy.yml
  .github/workflows/megalinter.yml
  .mega-linter.yml
  .yamllint.yml
  Dockerfile
  RELEASE_NOTES.md
  docker-compose.yml
  src/app/organization/bulk-import/bulk-import.component.html
  src/app/organization/bulk-import/view-bulk-import/bulk-imports.ts
Labels: size/XL

#241 Feat/cp 3502 add country to bulk account transfers
  RELEASE_NOTES.md
  package.json
  src/app/organization/bulk-import/view-bulk-import/view-bulk-import.component.ts
Labels: size/XS, untested

#239 cp-3538-show-transfer-description-in-repayment-view
  RELEASE_NOTES.md
  src/app/loans/loans-view/transactions/view-transaction/view-transaction.component.html
  src/assets/translations/en-US.json
  src/assets/translations/fr-FR.json
Labels: size/M
